(autoload 'egg-grep-find-file                   "egg-grep" "" nil)
(autoload 'egg-grep-next-error-function         "egg-grep" "" t)
(autoload 'egg-grep-process-setup               "egg-grep" "" nil)
(autoload 'egg-grep-mode                        "egg-grep" "" t)
(autoload 'egg-grep                             "egg-grep" "" t)
(autoload 'egg-text                             "egg" "" nil 'macro)
(autoload 'egg-prop                             "egg" "" nil 'macro)
(autoload 'egg-prepend                          "egg" "" nil);;defsubst
(autoload 'egg-commit-contents                  "egg" "" nil);;defsubst
(autoload 'egg-commit-message                   "egg" "" nil);;defsubst
(autoload 'egg-cmd-to-string-1                  "egg" "" nil);;defsubst
(autoload 'egg-cmd-to-string                    "egg" "" nil);;defsubst
(autoload 'egg-git-to-string                    "egg" "" nil);;defsubst
(autoload 'egg-cmd-ok                           "egg" "" nil);;defsubst
(autoload 'egg-git-ok                           "egg" "" nil);;defsubst
(autoload 'egg-git-region-ok                    "egg" "" nil);;defsubst
(autoload 'egg-wdir-clean                       "egg" "" nil);;defsubst
(autoload 'egg-file-updated                     "egg" "" nil);;defsubst
(autoload 'egg-file-committed                   "egg" "" nil);;defsubst
(autoload 'egg-file-index-empty                 "egg" "" nil);;defsubst
(autoload 'egg-index-empty                      "egg" "" nil);;defsubst
(autoload 'egg-git-to-lines                     "egg" "" nil);;defsubst
(autoload 'egg-git-lines-matching               "egg" "" nil)
(autoload 'egg-git-lines-matching-multi         "egg" "" nil)
(autoload 'egg-file-git-name                    "egg" "" nil);;defsubst
(autoload 'egg-buf-git-name                     "egg" "" nil);;defsubst
(autoload 'egg-files-git-name                   "egg" "" nil);;defsubst
(autoload 'egg-unmerged-files                   "egg" "" nil);;defsubst
(autoload 'egg-local-branches                   "egg" "" nil);;defsubst
(autoload 'egg-local-refs                       "egg" "" nil);;defsubst
(autoload 'egg-remote-branches                  "egg" "" nil)
(autoload 'egg-rbranch-to-remote                "egg" "" nil);;defsubst
(autoload 'egg-rbranch-name                     "egg" "" nil);;defsubst
(autoload 'egg-short-ref                        "egg" "" nil);;defsubst
(autoload 'egg-file-as-string-raw               "egg" "" nil);;defsubst
(autoload 'egg-file-as-string                   "egg" "" nil);;defsubst
(autoload 'egg-pick-file-contents               "egg" "" nil)
(autoload 'egg-pick-file-records                "egg" "" nil)
(autoload 'egg-is-in-git                        "egg" "" nil);;defsubst
(autoload 'egg-is-dir-in-git                    "egg" "" nil);;defsubst
(autoload 'egg-name-rev                         "egg" "" nil);;defsubst
(autoload 'egg-describe-rev                     "egg" "" nil);;defsubst
(autoload 'egg-sha1                             "egg" "" nil);;defsubst
(autoload 'egg-read-git-dir                     "egg" "" nil)
(autoload 'egg-read-dir-git-dir                 "egg" "" nil);;defsubst
(autoload 'egg-git-dir                          "egg" "" nil);;defsubst
(autoload 'egg-buf-git-dir                      "egg" "" nil);;defsubst
(autoload 'egg-HEAD                             "egg" "" nil)
(autoload 'egg-all-refs                         "egg" "" nil)
(autoload 'egg-ref-type-alist                   "egg" "" nil)
(autoload 'egg-tooltip-func                     "egg" "" nil);;defsubst
(autoload 'egg-full-ref-decorated-alist         "egg" "" nil)
(autoload 'egg-complete-rev                     "egg" "" nil)
(autoload 'egg-get-symbolic-HEAD                "egg" "" nil);;defsubst
(autoload 'egg-get-full-symbolic-HEAD           "egg" "" nil);;defsubst
(autoload 'egg-get-current-sha1                 "egg" "" nil);;defsubst
(autoload 'egg-set-mode-info                    "egg" "" nil);;defsubst
(autoload 'egg-get-rebase-merge-state           "egg" "" nil);;defsubst
(autoload 'egg-get-rebase-interactive-state     "egg" "" nil);;defsubst
(autoload 'egg-git-rebase-dir                   "egg" "" nil);;defsubst
(autoload 'egg-rebase-author-info               "egg" "" nil);;defsubst
(autoload 'egg-interactive-rebase-in-progress   "egg" "" nil);;defsubst
(autoload 'egg-get-repo-state                   "egg" "" nil)
(autoload 'egg-repo-state                       "egg" "" nil);;defsubst
(autoload 'egg-repo-clean                       "egg" "" nil);;defsubst
(autoload 'egg-current-branch                   "egg" "" nil);;defsubst
(autoload 'egg-current-sha1                     "egg" "" nil);;defsubst
(autoload 'egg-head                             "egg" "" nil);;defsubst
(autoload 'egg-pretty-head-string               "egg" "" nil)
(autoload 'egg-pretty-head-name                 "egg" "" nil);;defsubst
(autoload 'egg-config-section-raw               "egg" "" nil);;defsubst
(autoload 'egg-config-section                   "egg" "" nil);;defsubst
(autoload 'egg-config-get-all                   "egg" "" t)
(autoload 'egg-config-get-all-branches          "egg" "" nil);;defsubst
(autoload 'egg-config-get-all-remotes           "egg" "" nil);;defsubst
(autoload 'egg-config-get-all-remote-names      "egg" "" nil);;defsubst
(autoload 'egg-config-get                       "egg" "" nil);;defsubst
(autoload 'egg-tracking-target                  "egg" "" nil)
(autoload 'egg-read-rev                         "egg" "" nil);;defsubst
(autoload 'egg-read-remote                      "egg" "" nil);;defsubst
(autoload 'egg-async-process                    "egg" "" nil);;defsubst
(autoload 'egg-async-do                         "egg" "" nil)
(autoload 'egg-async-0                          "egg" "" nil);;defsubst
(autoload 'egg-async-1                          "egg" "" nil);;defsubst
(autoload 'egg-process-sentinel                 "egg" "" nil)
(autoload 'egg-parse-git-blame                  "egg" "" nil)
(autoload 'egg-file-buffer-blame-off            "egg" "" nil);;defsubst
(autoload 'egg-file-buffer-blame-on             "egg" "" nil)
(autoload 'egg-blame-locate-commit              "egg" "" t)
(autoload 'egg-mouse-do-command                 "egg" "" nil)
(autoload 'egg-mouse-hide-show-cmd              "egg" "" t)
(autoload 'list-tp                              "egg" "" t)
(autoload 'list-nav                             "egg" "" t)
(autoload 'egg-navigation-at-point              "egg" "" nil);;defsubst
(autoload 'egg-invisible-spec-at-point          "egg" "" nil);;defsubst
(autoload 'egg-hunk-at-point                    "egg" "" nil);;defsubst
(autoload 'egg-diff-at-point                    "egg" "" nil);;defsubst
(autoload 'egg-point-in-section                 "egg" "" nil);;defsubst
(autoload 'egg-safe-search                      "egg" "" nil);;defsubst
(autoload 'egg-safe-search-pickup               "egg" "" nil);;defsubst
(autoload 'egg-decorate-diff-header             "egg" "" nil);;defsubst
(autoload 'egg-decorate-cc-diff-header          "egg" "" nil);;defsubst
(autoload 'egg-decorate-diff-index-line         "egg" "" nil);;defsubst
(autoload 'egg-decorate-hunk-header             "egg" "" nil);;defsubst
(autoload 'egg-make-navigation                  "egg" "" nil);;defsubst
(autoload 'egg-do-compute-navigation            "egg" "" nil);;defsubst
(autoload 'egg-compute-navigation               "egg" "" nil)
(autoload 'egg-delimit-section                  "egg" "" nil)
(autoload 'egg-make-hunk-info                   "egg" "" nil);;defsubst
(autoload 'egg-make-diff-info                   "egg" "" nil);;defsubst
(autoload 'egg-decorate-diff-sequence           "egg" "" nil)
(autoload 'egg-decorate-diff-section            "egg" "" nil)
(autoload 'egg-diff-section-cmd-visit-file      "egg" "" t)
(autoload 'egg-diff-section-cmd-visit-file-other-window "egg" "" t)
(autoload 'egg-unmerged-section-cmd-ediff3      "egg" "" t)
(autoload 'egg-unstaged-section-cmd-ediff       "egg" "" t)
(autoload 'egg-staged-section-cmd-ediff3        "egg" "" t)
(autoload 'egg-diff-section-cmd-ediff           "egg" "" t)
(autoload 'egg-hunk-compute-line-no             "egg" "" nil)
(autoload 'egg-hunk-info-at                     "egg" "" nil);;defsubst
(autoload 'egg-hunk-section-cmd-visit-file      "egg" "" t)
(autoload 'egg-hunk-section-cmd-visit-file-other-window "egg" "" t)
(autoload 'egg-section-cmd-toggle-hide-show     "egg" "" t)
(autoload 'egg-section-cmd-toggle-hide-show-children "egg" "" t)
(autoload 'egg-diff-section-patch-string        "egg" "" nil)
(autoload 'egg-hunk-section-patch-string        "egg" "" nil)
(autoload 'egg-buffer-async-do                  "egg" "" nil);;defsubst
(autoload 'egg-run-buffers-update-hook          "egg" "" nil);;defsubst
(autoload 'egg-buffer-cmd-refresh               "egg" "" t)
(autoload 'egg-buffer-cmd-next-block            "egg" "" nil)
(autoload 'egg-buffer-cmd-prev-block            "egg" "" nil)
(autoload 'egg-buffer-cmd-navigate-next         "egg" "" t)
(autoload 'egg-buffer-cmd-navigate-prev         "egg" "" t)
(autoload 'egg-get-buffer                       "egg" "" nil)
(autoload 'egg-quit-buffer                      "egg" "" t)
(autoload 'define-egg-buffer                    "egg" "" nil 'macro)
(autoload 'egg-buffer-do-rebase                 "egg" "" nil)
(autoload 'egg-buffer-rebase-continue           "egg" "" t)
(autoload 'egg-do-async-rebase-continue         "egg" "" nil);;defsubst
(autoload 'egg-buffer-selective-rebase-action   "egg" "" nil)
(autoload 'egg-buffer-selective-rebase-continue "egg" "" t)
(autoload 'egg-buffer-selective-rebase-skip     "egg" "" t)
(autoload 'egg-buffer-rebase-skip               "egg" "" t)
(autoload 'egg-buffer-rebase-abort              "egg" "" t)
(autoload 'egg-rebase-in-progress               "egg" "" nil)
(autoload 'egg-pretty-help-text                 "egg" "" nil);;defsubst
(autoload 'egg-sb-insert-repo-section           "egg" "" nil)
(autoload 'egg-ignore-pattern-from-string-at-point "egg" "" t)
(autoload 'egg-status-buffer-stage-untracked-file "egg" "" t)
(autoload 'egg-sb-insert-untracked-section      "egg" "" nil)
(autoload 'egg-sb-insert-unstaged-section       "egg" "" nil)
(autoload 'egg-sb-insert-staged-section         "egg" "" nil)
(autoload 'egg-checkout-ref                     "egg" "" t)
(autoload 'egg-buffer-show-all                  "egg" "" t);;defsubst
(autoload 'egg-buffer-hide-all                  "egg" "" t);;defsubst
(autoload 'egg-buffer-hide-section-type         "egg" "" nil);;defsubst
(autoload 'egg-buffer-maybe-hide-all            "egg" "" nil);;defsubst
(autoload 'egg-buffer-maybe-hide-help           "egg" "" nil);;defsubst
(autoload 'egg-status-buffer-redisplay          "egg" "" nil)
(autoload 'egg-internal-background              "egg" "" nil)
(autoload 'egg-internal-background-refresh-index "egg" "" nil)
(autoload 'egg-status-buffer-background-job     "egg" "" nil)
(autoload 'egg-internal-background-jobs-restart "egg" "" nil);;defsubst
(autoload 'egg-set-background-idle-period       "egg" "" nil)
(autoload 'egg-status-make-section-menu         "egg" "" nil)
(autoload 'egg-status-popup-delta-menu          "egg" "" nil)
(autoload 'egg-status-popup-unstaged-diff-menu  "egg" "" t)
(autoload 'egg-status-popup-staged-diff-menu    "egg" "" t)
(autoload 'egg-status-popup-unstaged-hunk-menu  "egg" "" t)
(autoload 'egg-status-popup-staged-hunk-menu    "egg" "" t)
(autoload 'egg-status                           "egg" "" t)
(autoload 'egg-revert-visited-files             "egg" "" nil)
(autoload 'egg-revert-all-visited-files         "egg" "" nil)
(autoload 'egg-cmd-log-buffer                   "egg" "" nil)
(autoload 'egg-cmd-log                          "egg" "" nil);;defsubst
(autoload 'egg-sync-handle-exit-code            "egg" "" nil)
(autoload 'egg-sync-do                          "egg" "" nil)
(autoload 'egg-sync-do-region-0                 "egg" "" nil);;defsubst
(autoload 'egg-sync-0                           "egg" "" nil);;defsubst
(autoload 'egg-sync-do-region                   "egg" "" nil);;defsubst
(autoload 'egg-sync-git-region                  "egg" "" nil);;defsubst
(autoload 'egg-sync-do-file                     "egg" "" nil)
(autoload 'egg-hunk-section-patch-cmd           "egg" "" nil)
(autoload 'egg-show-git-output                  "egg" "" nil)
(autoload 'egg-hunk-section-cmd-stage           "egg" "" t)
(autoload 'egg-hunk-section-cmd-unstage         "egg" "" t)
(autoload 'egg-hunk-section-cmd-undo            "egg" "" t)
(autoload 'egg-diff-section-patch-cmd           "egg" "" nil)
(autoload 'egg-diff-section-cmd-stage           "egg" "" t)
(autoload 'egg-diff-section-cmd-unstage         "egg" "" t)
(autoload 'egg-diff-section-cmd-undo-old-no-revsion-check "egg" "" t)
(autoload 'egg-diff-section-cmd-undo            "egg" "" t)
(autoload 'egg-file-stage-current-file          "egg" "" t)
(autoload 'egg-stage-all-files                  "egg" "" t)
(autoload 'egg-do-stash-wip                     "egg" "" nil)
(autoload 'egg-do-checkout                      "egg" "" nil)
(autoload 'egg-do-tag                           "egg" "" nil)
(autoload 'egg-do-create-branch                 "egg" "" nil)
(autoload 'egg-do-apply-stash                   "egg" "" nil)
(autoload 'egg-do-pop-stash                     "egg" "" nil)
(autoload 'egg-do-move-head                     "egg" "" nil)
(autoload 'egg-do-merge-to-head                 "egg" "" nil)
(autoload 'egg-do-rebase-head                   "egg" "" nil)
(autoload 'egg-rm-ref                           "egg" "" nil)
(autoload 'egg-log-msg-mode                     "egg" "" t)
(autoload 'egg-log-msg-commit                   "egg" "" nil)
(autoload 'egg-log-msg-amend-commit             "egg" "" nil)
(autoload 'egg-log-msg-done                     "egg" "" t)
(autoload 'egg-log-msg-hist-cycle               "egg" "" nil)
(autoload 'egg-log-msg-older-text               "egg" "" t)
(autoload 'egg-log-msg-newer-text               "egg" "" t)
(autoload 'egg-commit-log-buffer-show-diffs     "egg" "" nil)
(autoload 'egg-commit-log-edit                  "egg" "" t)
(autoload 'egg-diff-buffer-insert-diffs         "egg" "" nil)
(autoload 'egg-diff-info-add-help               "egg" "" nil)
(autoload 'egg-do-diff                          "egg" "" nil)
(autoload 'egg-build-diff-info                  "egg" "" nil)
(autoload 'egg-run-git-log-HEAD                 "egg" "" nil)
(autoload 'egg-run-git-log-all                  "egg" "" nil)
(autoload 'egg-run-git-log-pickaxe              "egg" "" nil)
(autoload 'egg-decorate-log                     "egg" "" nil)
(autoload 'egg-log-buffer-insert-n-decorate-logs "egg" "" nil);;defsubst
(autoload 'egg-log-diff-cmd-visit-file          "egg" "" t)
(autoload 'egg-log-diff-cmd-visit-file-other-window "egg" "" t)
(autoload 'egg-log-hunk-cmd-visit-file          "egg" "" t)
(autoload 'egg-log-hunk-cmd-visit-file-other-window "egg" "" t)
(autoload 'egg-log-buffer-get-rev-at            "egg" "" nil)
(autoload 'egg-log-buffer-do-remove-mark        "egg" "" nil)
(autoload 'egg-log-buffer-find-first-mark       "egg" "" nil)
(autoload 'egg-log-buffer-do-mark               "egg" "" nil)
(autoload 'egg-log-buffer-mark                  "egg" "" t)
(autoload 'egg-log-buffer-mark-pick             "egg" "" t)
(autoload 'egg-log-buffer-mark-squash           "egg" "" t)
(autoload 'egg-log-buffer-mark-edit             "egg" "" t)
(autoload 'egg-log-buffer-do-unmark-all         "egg" "" t)
(autoload 'egg-log-buffer-unmark                "egg" "" t)
(autoload 'egg-log-buffer-get-marked-alist      "egg" "" nil)
(autoload 'egg-setup-rebase-interactive         "egg" "" nil)
(autoload 'egg-handle-rebase-interactive-exit   "egg" "" nil)
(autoload 'egg-log-buffer-merge                 "egg" "" t)
(autoload 'egg-log-buffer-rebase                "egg" "" t)
(autoload 'egg-log-buffer-rebase-interactive    "egg" "" t)
(autoload 'egg-log-buffer-checkout-commit       "egg" "" t)
(autoload 'egg-log-buffer-tag-commit            "egg" "" t)
(autoload 'egg-log-buffer-atag-commit           "egg" "" t)
(autoload 'egg-log-buffer-create-new-branch     "egg" "" t)
(autoload 'egg-log-buffer-start-new-branch      "egg" "" t)
(autoload 'egg-log-buffer-attach-head           "egg" "" t)
(autoload 'egg-log-buffer-rm-ref                "egg" "" t)
(autoload 'egg-log-buffer-fetch-remote-ref      "egg" "" t)
(autoload 'egg-log-buffer-fetch                 "egg" "" t)
(autoload 'egg-log-buffer-push-to-local         "egg" "" t)
(autoload 'egg-log-buffer-push-head-to-local    "egg" "" t)
(autoload 'egg-log-buffer-push-to-remote        "egg" "" t)
(autoload 'egg-log-buffer-push                  "egg" "" t)
(autoload 'egg-log-buffer-goto-pos              "egg" "" nil)
(autoload 'egg-log-buffer-next-ref              "egg" "" t)
(autoload 'egg-log-buffer-prev-ref              "egg" "" t)
(autoload 'egg-log-buffer-do-insert-commit      "egg" "" nil)
(autoload 'egg-log-buffer-insert-commit         "egg" "" t)
(autoload 'egg-generic-display-logs             "egg" "" nil)
(autoload 'egg-log-buffer-redisplay             "egg" "" nil)
(autoload 'egg-log-buffer-redisplay-from-command "egg" "" nil)
(autoload 'egg-commit-at-point                  "egg" "" nil)
(autoload 'egg-ref-at-point                     "egg" "" nil)
(autoload 'egg-head-at-point                    "egg" "" nil)
(autoload 'egg-tag-at-point                     "egg" "" nil)
(autoload 'egg-remote-at-point                  "egg" "" nil)
(autoload 'egg-references-at-point              "egg" "" nil)
(autoload 'egg-log-commit-line-menu-attach-head-index "egg" "" t)
(autoload 'egg-log-commit-line-menu-attach-head-index-wdir "egg" "" t)
(autoload 'egg-log-make-commit-line-menu        "egg" "" nil)
(autoload 'egg-log-commit-line-menu-heading     "egg" "" nil)
(autoload 'egg-log-commit-mouse-menu-heading    "egg" "" nil)
(autoload 'egg-log-popup-commit-line-menu-1     "egg" "" nil)
(autoload 'egg-log-popup-local-ref-menu         "egg" "" t)
(autoload 'egg-log-popup-remote-ref-menu        "egg" "" t)
(autoload 'egg-log-popup-remote-site-menu       "egg" "" t)
(autoload 'egg-log-popup-commit-line-menu       "egg" "" t)
(autoload 'egg-log-buffer-diff-revs             "egg" "" t)
(autoload 'egg-log                              "egg" "" t)
(autoload 'egg-run-git-file-log-HEAD            "egg" "" nil);;defsubst
(autoload 'egg-run-git-file-log-all             "egg" "" nil);;defsubst
(autoload 'egg-log-buffer-decorate-logs-simple  "egg" "" nil);;defsubst
(autoload 'egg-log-buffer-simple-redisplay      "egg" "" nil)
(autoload 'egg-file-log                         "egg" "" t)
(autoload 'egg-log-locate-commit                "egg" "" t)
(autoload 'egg-query:commit-buffer-rerun        "egg" "" t)
(autoload 'egg-insert-n-decorate-pickaxed-logs  "egg" "" nil)
(autoload 'egg-search-changes                   "egg" "" t)
(autoload 'egg-run-reflog-branch                "egg" "" nil);;defsubst
(autoload 'egg-reflog                           "egg" "" t)
(autoload 'egg-log-buffer-reflog-ref            "egg" "" t)
(autoload 'egg-list-stash                       "egg" "" nil);;defsubst
(autoload 'egg-stash-buffer-do-insert-stash     "egg" "" nil)
(autoload 'egg-stash-buffer-show                "egg" "" t)
(autoload 'egg-stash-buffer-pop                 "egg" "" t)
(autoload 'egg-stash-buffer-apply               "egg" "" t)
(autoload 'egg-buffer-stash-wip                 "egg" "" t)
(autoload 'egg-stash-buffer-next-stash          "egg" "" t)
(autoload 'egg-stash-buffer-prev-stash          "egg" "" t)
(autoload 'egg-decorate-stash-list              "egg" "" nil)
(autoload 'egg-stash-buffer-decorate-stash-list "egg" "" nil);;defsubst
(autoload 'egg-stash                            "egg" "" t)
(autoload 'egg-tag-msg-create-tag               "egg" "" nil)
(autoload 'egg-create-annotated-tag             "egg" "" nil)
(autoload 'egg-file-toggle-blame-mode           "egg" "" t)
(autoload 'egg-file-diff                        "egg" "" t)
(autoload 'egg-file-checkout-other-version      "egg" "" t)
(autoload 'egg-file-cancel-modifications        "egg" "" t)
(autoload 'egg-start-new-branch                 "egg" "" t)
(autoload 'egg-file-get-other-version           "egg" "" nil)
(autoload 'egg-file-version-other-window        "egg" "" t)
(autoload 'egg-file-ediff                       "egg" "" t)
(autoload 'egg-resolve-merge-with-ediff         "egg" "" t)
(autoload 'egg-file-do-ediff                    "egg" "" nil)
(autoload 'egg-select-action-run                "egg" "" t)
(autoload 'egg-select-action-quit               "egg" "" t)
(autoload 'egg-electric-select-action           "egg" "" nil)
(autoload 'egg-guess-next-action                "egg" "" nil);;defsubst
(autoload 'egg-limit-alternative-actions        "egg" "" nil)
(autoload 'egg-describe-state                   "egg" "" nil)
(autoload 'egg-build-key-prompt                 "egg" "" nil);;defsubst
(autoload 'egg-prompt-next-action               "egg" "" nil)
(autoload 'egg-next-action                      "egg" "" t)
(autoload 'egg-file-next-action-menu-name       "egg" "" nil)
(autoload 'egg-file-next-action-menu-binding    "egg" "" nil)
(autoload 'egg-mode-key-prefix-set              "egg" "" nil)
(autoload 'egg-file-log-pickaxe                 "egg" "" t)
(autoload 'egg-minor-mode                       "egg" "" t)
(autoload 'egg-minor-mode-find-file-hook        "egg" "" nil)
(autoload 'egg-ref-at                           "egg" "" nil)
(autoload 'egg-ref-or-commit-at                 "egg" "" nil)
(autoload 'egg-commit-at                        "egg" "" nil)
(autoload 'egg-rsite-at                         "egg" "" nil)
(autoload 'egg-delta-file-at                    "egg" "" nil)
(autoload 'egg-delta-hunk-at                    "egg" "" nil)
(autoload 'egg-section-at                       "egg" "" nil)
(autoload 'egg-file-name-at                     "egg" "" nil)
(autoload 'egg-buffer-help-echo                 "egg" "" nil)
(provide 'egg-epackage-autoloads)
